import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { isMobile } from "react-device-detect";
import styles from "../styles/Home.module.css";
import { DATA_BUTTON, DATA_CONTENT } from "./store/data";

const Home: NextPage = () => {
  const [text, setText] = useState(DATA_CONTENT[0].text);
  const [textButton, setTextButton] = useState(DATA_BUTTON[0].text);
  const [bg, setBg] = useState("");

  const randomText = () => {
    const numberRandom = Math.floor(Math.random() * 10) + 1;
    const numberButtonRandom = Math.floor(Math.random() * 2) + 1;

    setText(DATA_CONTENT[numberRandom].text);
    setTextButton(DATA_BUTTON[numberButtonRandom].text);
  };

  const changeBg = () => {
    const numberFrom1To8 = Math.floor(Math.random() * 8) + 1;

    if (isMobile) {
      setBg(`https://www.picsum.photos/900/160${numberFrom1To8}`);
    } else {
      setBg(`https://www.picsum.photos/1600/90${numberFrom1To8}`);
    }
  };

  const getUniverse = () => {
    randomText();
  };

  useEffect(() => {
    if (isMobile) {
      setBg("https://picsum.photos/900/1600");
    } else {
      setBg("https://picsum.photos/1600/900");
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={styles.base}
        style={{
          background: `url(${bg})`,
        }}
      >
        <div className={styles.content}>
          <div className={styles.text}>{text}</div>
          <div className={styles.btnContainer}>
            <div className={styles.buttonText} onClick={() => getUniverse()}>
              {textButton}
            </div>
          </div>
        </div>
        <div className={styles.changBG}>
          <div
            className={styles.buttonRandomAnimation}
            onClick={() => changeBg()}
          />
          <div className={styles.buttonChangeBG} onClick={() => changeBg()} />
          <div className={styles.buttonIDontKnow} onClick={() => changeBg()} />
        </div>
      </div>
    </div>
  );
};

export default Home;
